# TCL File Generated by Component Editor 24.1
# Sun May 11 18:09:45 EEST 2025
# DO NOT MODIFY


# 
# AES_AXI "AES_AXI" v1.0
#  2025.05.11.18:09:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AES_AXI
# 
set_module_property DESCRIPTION ""
set_module_property NAME AES_AXI
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AES_AXI
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AES_AXI_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AES_top.v VERILOG PATH RTL/AES_top.v
add_fileset_file AddRoundKey.v VERILOG PATH RTL/AddRoundKey.v
add_fileset_file KeyExpansion.v VERILOG PATH RTL/KeyExpansion.v
add_fileset_file MixColumns.v VERILOG PATH RTL/MixColumns.v
add_fileset_file ShiftRows.v VERILOG PATH RTL/ShiftRows.v
add_fileset_file SubByte.v VERILOG PATH RTL/SubByte.v
add_fileset_file invSbox.v VERILOG PATH RTL/invSbox.v
add_fileset_file invSubByte.v VERILOG PATH RTL/invSubByte.v
add_fileset_file sbox.v VERILOG PATH RTL/sbox.v
add_fileset_file AES_AXI_wrapper.v VERILOG PATH RTL/AES_AXI_wrapper.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL AES_AXI_wrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file AES_top.v VERILOG PATH RTL/AES_top.v
add_fileset_file AddRoundKey.v VERILOG PATH RTL/AddRoundKey.v
add_fileset_file KeyExpansion.v VERILOG PATH RTL/KeyExpansion.v
add_fileset_file MixColumns.v VERILOG PATH RTL/MixColumns.v
add_fileset_file ShiftRows.v VERILOG PATH RTL/ShiftRows.v
add_fileset_file SubByte.v VERILOG PATH RTL/SubByte.v
add_fileset_file invSbox.v VERILOG PATH RTL/invSbox.v
add_fileset_file invSubByte.v VERILOG PATH RTL/invSubByte.v
add_fileset_file sbox.v VERILOG PATH RTL/sbox.v
add_fileset_file AES_AXI_wrapper.v VERILOG PATH RTL/AES_AXI_wrapper.v


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 6
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 6
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink ACLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink ARESETN reset_n Input 1


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock_sink
set_interface_property altera_axi4lite_slave associatedReset reset_sink
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave S_AXI_AWADDR awaddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave S_AXI_AWVALID awvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_AWREADY awready Output 1
add_interface_port altera_axi4lite_slave S_AXI_WDATA wdata Input 32
add_interface_port altera_axi4lite_slave S_AXI_WSTRB wstrb Input "(((DATA_WIDTH/8)-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave S_AXI_WVALID wvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_WREADY wready Output 1
add_interface_port altera_axi4lite_slave S_AXI_BRESP bresp Output 2
add_interface_port altera_axi4lite_slave S_AXI_BVALID bvalid Output 1
add_interface_port altera_axi4lite_slave S_AXI_BREADY bready Input 1
add_interface_port altera_axi4lite_slave S_AXI_ARADDR araddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave S_AXI_ARVALID arvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_ARREADY arready Output 1
add_interface_port altera_axi4lite_slave S_AXI_RDATA rdata Output 32
add_interface_port altera_axi4lite_slave S_AXI_RRESP rresp Output 2
add_interface_port altera_axi4lite_slave S_AXI_RVALID rvalid Output 1
add_interface_port altera_axi4lite_slave S_AXI_RREADY rready Input 1

